### ISSUE TITLE
Fatal Error in RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#206]
````
Fatal error: Uncaught exception \'UnexpectedValueException\' with message \'RecursiveDirectoryIterator::__construct(/): failed to open dir: No error\' in D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php:978
Stack trace:
#0 D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(978): RecursiveDirectoryIterator->__construct(\'/\', 512)
#1 D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(819): HM_Backup->get_files()
#2 D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(753): HM_Backup->zip_archive()
#3 D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(619): HM_Backup->archive()
#4 D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\classes\\schedule.php(5 in D:\\inetpub\\vhosts\\circleconsultingagency.com\\httpdocs\\wdata\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php on line 978
````

**Comment by willmot** [comment]
closing as we don't even use hm-backup anymore
